[package]
name = "seiran"
version = "0.1.0"
authors = ["gyara <me@gyara.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
env_logger = "0.8.2"
log = "0.4.14"
reqwest = { version = "0.11.1", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0.123"
serde_json = "1.0.61"
tokio = { version = "1.1.0", features = ["rt", "rt-multi-thread"], default-features=false }
